
version: 2

models:
  - name: customlobby
    description: Extracted players data from raw JSON
    columns:
      - name: playerToken
        description: The token associated with the player
      - name: name
        description: The name of the player
      - name: teamId
        description: The team ID of the player
      - name: nucleusHash
        description: The nucleus hash associated with the player
      - name: hardwareName
        description: The name of the hardware the player is using

  - name: success
    description: Status of the operation
    columns:
      - name: success
        description: Boolean value indicating if the operation was successful or not

  - name: init
    description: Initialization data from raw JSON
    columns:
      - name: timestamp
        description: The timestamp of the event
      - name: category
        description: The category of the event
      - name: gameVersion
        description: The game version associated with the event
      - name: apiVersion
        description: The API version associated with the event
