version: 2

sources:
  - name: json
    schema: pubsub
    tables:
      - name: apex

models:
  - name: json_table
    description: Players data from raw JSON
    columns:
      - name: data
        description: The raw json data