name: dbt_deploy
on:
  push:
      branches:
        - main
env:
  DBT_PROFILES_DIR: ./

  DBT_GOOGLE_PROJECT: ${{ secrets.DBT_GOOGLE_PROJECT }}
  DBT_GOOGLE_BIGQUERY_DATASET: ${{ secrets.DBT_GOOGLE_BIGQUERY_DATASET }}
  DBT_GOOGLE_BIGQUERY_KEYFILE: ./dbt-service-account.json

jobs:
  scheduled_run:
    name: scheduled_run
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@master

      - uses: actions/setup-python@v1
        with:
          python-version: "3.8.x"

      - name: Authenticate using service account
        run: 'echo "$KEYFILE" > ./dbt-service-account.json'
        shell: bash
        env:
          KEYFILE: ${{secrets.DBT_GOOGLE_BIGQUERY_KEYFILE}}

      - name: Install dependencies
        run: |
          pip install dbt-bigquery
          dbt deps
      
      - name: Run dbt models
        run: dbt run

      - name: Generate dbt docs
        run: dbt docs generate

      - name: Move docs to docs folder
        run: mv target/ docs/

      - name: Git setup
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Commit and push dbt docs
        run: |
          git add docs/
          git commit -m "Update dbt docs"
          git push origin main
